export enum Category {
  Acaricide = "Acaricide",
  SoilConditioner = "Soil Conditioner",
  SolarBlockerApple = "Solar Blocker Apple",
  AntitranspirantAdjuvant = "Antitranspirant Adjuvant",
  Detergent = "Detergent",
  Containers = "Containers",
  Fertilizer = "Fertilizer",
  Filter = "Filter",
  Fungicide = "Fungicide",
  Herbicide = "Herbicide",
  Herbicide2 = "Herbicide2",
  Inoculant = "Inoculant",
  InsecticideAcaricide = "Insecticide Acaricide",
  Nematicide = "Nematicide",
  PaceInternational = "Pace International",
  OrganicCoating = "Organic Coating",
  GrowthRegulator = "Growth Regulator",
}
