import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  addDoc,
  connectFirestoreEmulator,
} from "firebase/firestore";
import {
  getAuth,
  signInWithEmailAndPassword,
  connectAuthEmulator,
} from "firebase/auth";

// Firebase config for emulator
const firebaseConfig = {
  apiKey: "fake-api-key",
  authDomain: "localhost",
  projectId: "stockflow-wms",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

// Connect to emulators
connectFirestoreEmulator(db, "localhost", 8080);
connectAuthEmulator(auth, "http://localhost:9099");

const products = [
  {
    extCode: "ECTSL09500MYCCH",
    internalCode: "INT001",
    name: "endofuse (500 cc)",
    price: 100,
    warehouseStock: 77,
    riskCategory: "NonToxic",
    category: "Herbicide",
    selectionType: "unit",
    boxDetails: {
      units: 8,
      quantity: 500,
      unitOfMeasure: "ML",
      container: "Bidones",
      type: "Plastic",
      kilos: 1,
      height: 20,
      width: 10,
      depth: 10,
      unitsPerSurface: 4,
      palletType: "Standard",
    },
  },
  {
    extCode: "FENWG50001VALCH",
    internalCode: "INT002",
    name: "kamuy 50 wg (1 kgs)",
    price: 200,
    warehouseStock: 143,
    riskCategory: "Toxic",
    category: "Fungicide",
    selectionType: "unit",
    boxDetails: {
      units: 10,
      quantity: 1000,
      unitOfMeasure: "Gram",
      container: "Bolsas",
      type: "Paper",
      kilos: 2.5,
      height: 15,
      width: 8,
      depth: 8,
      unitsPerSurface: 2,
      palletType: "Standard",
    },
  },
  {
    extCode: "FLPWP50100VALCH",
    internalCode: "INT003",
    name: "pledge 50% wp (100 grs)",
    price: 150,
    warehouseStock: 1,
    riskCategory: "Toxic",
    category: "Herbicide",
    selectionType: "unit",
    boxDetails: {
      units: 100,
      quantity: 100,
      unitOfMeasure: "Gram",
      container: "Bolsa",
      type: "Paper",
      kilos: 1.2,
      height: 18,
      width: 9,
      depth: 9,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
  {
    extCode: "FLVWP50100VALCH",
    internalCode: "INT004",
    name: "valor 50% wp (100 grs)",
    price: 120,
    warehouseStock: 10,
    riskCategory: "Toxic",
    category: "Herbicide",
    selectionType: "unit",
    boxDetails: {
      units: 100,
      quantity: 100,
      unitOfMeasure: "Gram",
      container: "Bolsa",
      type: "Paper",
      kilos: 0.8,
      height: 16,
      width: 8,
      depth: 8,
      unitsPerSurface: 5,
      palletType: "Standard",
    },
  },
  {
    extCode: "GIBSG40025VALCH",
    internalCode: "INT005",
    name: "progibb 40% sg (2,5 grs)",
    price: 180,
    warehouseStock: 357000,
    riskCategory: "NonToxic",
    category: "Fitorregulador",
    selectionType: "unit",
    boxDetails: {
      units: 800,
      quantity: 2.5,
      unitOfMeasure: "Gram",
      container: "Bolsa",
      type: "Paper",
      kilos: 2.0,
      height: 14,
      width: 7,
      depth: 7,
      unitsPerSurface: 2,
      palletType: "Standard",
    },
  },
  {
    extCode: "GIBSG40250VALCH",
    internalCode: "INT006",
    name: "progibb 40% sg (250 grs)",
    price: 90,
    warehouseStock: 3046,
    riskCategory: "NonToxic",
    category: "Fitorregulador",
    selectionType: "unit",
    boxDetails: {
      units: 10,
      quantity: 250,
      unitOfMeasure: "Gram",
      container: "Botellas",
      type: "Plastic",
      kilos: 1.5,
      height: 22,
      width: 11,
      depth: 11,
      unitsPerSurface: 6,
      palletType: "Standard",
    },
  },
  {
    extCode: "LFSL230220ITACH",
    internalCode: "INT007",
    name: "surft ts 2035 (220 kgs)",
    price: 210,
    warehouseStock: 3740,
    riskCategory: "Toxic",
    category: "Detergente Frutal",
    selectionType: "unit",
    boxDetails: {
      units: 1,
      quantity: 220,
      unitOfMeasure: "L",
      container: "Tambores",
      type: "Metal",
      kilos: 2.2,
      height: 19,
      width: 10,
      depth: 10,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
  {
    extCode: "MAGSL04010ANACH",
    internalCode: "INT008",
    name: "brandt manni plex mg (10 ltrs)",
    price: 160,
    warehouseStock: 30,
    riskCategory: "NonToxic",
    category: "Fertilizante",
    selectionType: "unit",
    boxDetails: {
      units: 2,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.1,
      height: 13,
      width: 6,
      depth: 6,
      unitsPerSurface: 2,
      palletType: "Standard",
    },
  },
  {
    extCode: "MCPASL7510NUFCH",
    internalCode: "INT009",
    name: "mcpa 750 sl (1x10l)",
    price: 130,
    warehouseStock: 10,
    riskCategory: "Toxic",
    category: "Herbicide",
    selectionType: "unit",
    boxDetails: {
      units: 1,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.3,
      height: 17,
      width: 8,
      depth: 8,
      unitsPerSurface: 4,
      palletType: "Standard",
    },
  },
  {
    extCode: "MICPS01500MYCCH",
    internalCode: "INT010",
    name: "endosmart (500 grs)",
    price: 175,
    warehouseStock: 93,
    riskCategory: "NonToxic",
    category: "Inoculante Biologico",
    selectionType: "unit",
    boxDetails: {
      units: 10,
      quantity: 500,
      unitOfMeasure: "Gram",
      container: "Bolsa",
      type: "Paper",
      kilos: 1.7,
      height: 21,
      width: 12,
      depth: 12,
      unitsPerSurface: 5,
      palletType: "Standard",
    },
  },
  {
    extCode: "NPKSL27010ANACH",
    internalCode: "INT011",
    name: "brandt plant start (10 ltrs)",
    price: 140,
    warehouseStock: 59630,
    riskCategory: "NonToxic",
    category: "Fertilizante",
    selectionType: "unit",
    boxDetails: {
      units: 2,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.9,
      height: 15,
      width: 7,
      depth: 7,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
  {
    extCode: "PINEC9600413MIL",
    internalCode: "INT012",
    name: "nufilm - 17  x 4 lts.",
    price: 155,
    warehouseStock: 10024,
    riskCategory: "Toxic",
    category: "Coadyuvante",
    selectionType: "unit",
    boxDetails: {
      units: 4,
      quantity: 4,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.4,
      height: 18,
      width: 9,
      depth: 9,
      unitsPerSurface: 2,
      palletType: "Standard",
    },
  },
  {
    extCode: "POTSL20010ANACH",
    internalCode: "INT013",
    name: "brandt manni plex k (10 ltrs)",
    price: 195,
    warehouseStock: 6900,
    riskCategory: "Toxic",
    category: "Fertilizante",
    selectionType: "unit",
    boxDetails: {
      units: 2,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 2.1,
      height: 23,
      width: 13,
      depth: 13,
      unitsPerSurface: 6,
      palletType: "Standard",
    },
  },
  {
    extCode: "TBCSC66001BAYCH",
    internalCode: "INT014",
    name: "tie break 416,7 sc  (1 lt)",
    price: 170,
    warehouseStock: 6967,
    riskCategory: "NonToxic",
    category: "Fungicide",
    selectionType: "unit",
    boxDetails: {
      units: 12,
      quantity: 1,
      unitOfMeasure: "L",
      container: "Botellas",
      type: "Glass",
      kilos: 1.6,
      height: 16,
      width: 8,
      depth: 8,
      unitsPerSurface: 4,
      palletType: "Standard",
    },
  },
  {
    extCode: "UNGSC05005AQUCH",
    internalCode: "INT015",
    name: "sumagic 5 sc (5 ltrs)",
    price: 145,
    warehouseStock: 1220,
    riskCategory: "NonToxic",
    category: "Fitorregulador",
    selectionType: "unit",
    boxDetails: {
      units: 4,
      quantity: 5,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.8,
      height: 19,
      width: 9,
      depth: 9,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
  {
    extCode: "CALSL10010ANACH",
    internalCode: "INT016",
    name: "brandt manni plex  ca  (10 ltrs)",
    price: 165,
    warehouseStock: 6000,
    riskCategory: "NonToxic",
    category: "Fertilizante",
    selectionType: "unit",
    boxDetails: {
      units: 2,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.3,
      height: 17,
      width: 8,
      depth: 8,
      unitsPerSurface: 4,
      palletType: "Standard",
    },
  },
  {
    extCode: "ECTPC01500MYCCH",
    internalCode: "INT017",
    name: "ectoverde (500 grs)",
    price: 135,
    warehouseStock: 694,
    riskCategory: "NonToxic",
    category: "Inoculante Biologico",
    selectionType: "unit",
    boxDetails: {
      units: 10,
      quantity: 500,
      unitOfMeasure: "Gram",
      container: "Bolsa",
      type: "Paper",
      kilos: 1.5,
      height: 16,
      width: 8,
      depth: 8,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
  {
    extCode: "6BESL02010VALCH",
    internalCode: "INT018",
    name: "cylex x 10 ltrs.",
    price: 185,
    warehouseStock: 1730,
    riskCategory: "NonToxic",
    category: "Fitorregulador",
    selectionType: "unit",
    boxDetails: {
      units: 2,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.7,
      height: 20,
      width: 10,
      depth: 10,
      unitsPerSurface: 4,
      palletType: "Standard",
    },
  },
  {
    extCode: "ACSSL10002VALCH",
    internalCode: "INT019",
    name: "protone sl (2 ltrs)",
    price: 125,
    warehouseStock: 392,
    riskCategory: "NonToxic",
    category: "Fitorregulador",
    selectionType: "unit",
    boxDetails: {
      units: 4,
      quantity: 2,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.2,
      height: 15,
      width: 7,
      depth: 7,
      unitsPerSurface: 2,
      palletType: "Standard",
    },
  },
  {
    extCode: "ACTSC02001SCBCH",
    internalCode: "INT020",
    name: "acetamiprid 200 sc (1 lts)",
    price: 190,
    warehouseStock: 5229,
    riskCategory: "Toxic",
    category: "Insecticide",
    selectionType: "unit",
    boxDetails: {
      units: 12,
      quantity: 1,
      unitOfMeasure: "L",
      container: "Botellas",
      type: "Glass",
      kilos: 1.8,
      height: 18,
      width: 9,
      depth: 9,
      unitsPerSurface: 5,
      palletType: "Standard",
    },
  },
  {
    extCode: "AMISL11003VBCCH",
    internalCode: "INT021",
    name: "accede sl 4 x 3l",
    price: 155,
    warehouseStock: 207,
    riskCategory: "NonToxic",
    category: "Pesticida",
    selectionType: "unit",
    boxDetails: {
      units: 4,
      quantity: 3,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.4,
      height: 16,
      width: 8,
      depth: 8,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
  {
    extCode: "BACWG64500VALCH",
    internalCode: "INT022",
    name: "dipel wg (500 grs)",
    price: 175,
    warehouseStock: 480,
    riskCategory: "NonToxic",
    category: "Insecticida Biologico",
    selectionType: "unit",
    boxDetails: {
      units: 24,
      quantity: 500,
      unitOfMeasure: "Gram",
      container: "Botellas",
      type: "Plastic",
      kilos: 1.6,
      height: 17,
      width: 9,
      depth: 9,
      unitsPerSurface: 4,
      palletType: "Standard",
    },
  },
  {
    extCode: "BORSL03010ANACH",
    internalCode: "INT023",
    name: "brandt manni plex b moly (10 ltrs)",
    price: 165,
    warehouseStock: 6000,
    riskCategory: "Toxic",
    category: "Fertilizante",
    selectionType: "unit",
    boxDetails: {
      units: 2,
      quantity: 10,
      unitOfMeasure: "L",
      container: "Bidones",
      type: "Plastic",
      kilos: 1.9,
      height: 19,
      width: 10,
      depth: 10,
      unitsPerSurface: 3,
      palletType: "Standard",
    },
  },
];

async function main() {
  // Authenticate as test user
  await signInWithEmailAndPassword(auth, "admin@gmail.com", "123456");

  for (const product of products) {
    await addDoc(collection(db, "products"), product);
    console.log(`Added product: ${product.name}`);
  }
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
